version: '3.8'

networks:
  shopsphere-network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '@Lodigoud25'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shopsphere-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p@Lodigoud25" ]
      interval: 15s
      timeout: 10s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shopsphere-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 15s
      timeout: 10s
      retries: 10

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - shopsphere-network

  eureka-server:
    build:
      context: ./eureka-server/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - shopsphere-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 10

  config-server:
    build:
      context: ./config-server/config-server
    container_name: config-server
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "github.com:140.82.121.4"
      - "objects.githubusercontent.com:185.199.108.133"
    ports:
      - "8888:8888"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/yellendhar08/shopsphere-config-docker
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"
    networks:
      - shopsphere-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 15s
      timeout: 10s
      retries: 10

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - shopsphere-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  auth-service:
    build:
      context: ./auth-service/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - shopsphere-network
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  catalog-service:
    build:
      context: ./catalog-service/catalog-service
    container_name: catalog-service
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - shopsphere-network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service/order-service
    container_name: order-service
    ports:
      - "8083:8083"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - shopsphere-network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  admin-service:
    build:
      context: ./admin-service/admin-service
    container_name: admin-service
    ports:
      - "8084:8084"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - shopsphere-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - shopsphere-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  mysql-data: