server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yellendhar08/shopsphere-config-docker
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yellendhar08/shopsphere-config
          default-label: main
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/